### global variables
@baseURL = http://localhost:3001
@contentType = application/json

### homepage
GET {{baseURL}}

### persons

GET {{baseURL}}/api/persons

### persons item get 
GET {{baseURL}}/api/persons/5ed798669ebf581084ab4490

### persons item post 
POST  {{baseURL}}/api/persons
Content-Type: {{contentType}}

{        
    "name": "empty number", 
    "number": "234432-12-739"
}

### persons item post (test for name uniqueness)
POST  {{baseURL}}/api/persons
Content-Type: {{contentType}}

{        
    "name": "Dan Abramov", 
    "number": "00-00-000000" 
}

### persons item delete
DELETE  {{baseURL}}/api/persons/5ed798669ebf581084ab4492

### persons item update
PUT {{baseURL}}/api/persons/5ed798669ebf581084ab4492
Content-Type: {{contentType}}

{
    "name": "John M. Doe",
    "number": "40-12-5555122"    
}

### info 
GET {{baseURL}}/info

### unknown endpoint
GET {{baseURL}}/foo/bar



