### global variables
@baseURL = http://localhost:3001
@contentType = application/json

### homepage
GET {{baseURL}}

### persons

GET {{baseURL}}/api/persons

### persons item get 
GET {{baseURL}}/api/persons/5ed798669ebf581084ab4490

### persons item post 
POST  {{baseURL}}/api/persons
Content-Type: {{contentType}}

{        
    "name": "test contact", 
    "number": "739-12-987432"
}

### persons item post (test for name uniqueness)
POST  {{baseURL}}/api/persons
Content-Type: {{contentType}}

{        
    "name": "Dan Abramov", 
    "number": "12-43-234345" 
}

### persons item delete
DELETE  {{baseURL}}/api/persons/10

### info 
GET {{baseURL}}/info

### unknown endpoint
GET {{baseURL}}/foo/bar


