### global variables
@baseURL = http://localhost:3001
@contentType = application/json

### notes

GET {{baseURL}}/api/persons/

### notes item get 
GET {{baseURL}}/api/persons/1

### notes item post 
POST  {{baseURL}}/api/persons/
Content-Type: {{contentType}}

{        
    "name": "John Doe", 
    "number": "739-12-987432"
}

### info 
GET {{baseURL}}/info


